// src/redux/ticket/ticketTypes.js

export const FETCH_TICKETS_CUSTOMER_REQUEST = 'FETCH_TICKETS_CUSTOMER_REQUEST';
export const FETCH_TICKETS_CUSTOMER_SUCCESS = 'FETCH_TICKETS_CUSTOMER_SUCCESS';
export const FETCH_TICKETS_CUSTOMER_FAILURE = 'FETCH_TICKETS_CUSTOMER_FAILURE';
