export const FETCH_TICKETS_MANAGER_STATUS_REQUEST = "FETCH_TICKETS_REQUEST";
export const FETCH_TICKETS_MANAGER_STATUS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_MANAGER_STATUS_FAILURE = "FETCH_TICKETS_FAILURE";
