// src/redux/ticket/ticketTypes.js

export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_TABLE_REQUEST';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_TABLE_SUCCESS';
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_TABLE_FAILURE';
