export const FETCH_TICKETS_EMPLOYEE_REQUEST = "FETCH_TICKETS_EMPLOYEE_REQUEST";
export const FETCH_TICKETS_EMPLOYEE_SUCCESS = "FETCH_TICKETS_EMPLOYEE_SUCCESS";
export const FETCH_TICKETS_EMPLOYEE_FAILURE = "FETCH_TICKETS_EMPLOYEE_FAILURE";

export const UPDATE_TICKET_STATUS_REQUEST = "UPDATE_TICKET_STATUS_REQUEST";
export const UPDATE_TICKET_STATUS_SUCCESS = "UPDATE_TICKET_STATUS_SUCCESS";
export const UPDATE_TICKET_STATUS_FAILURE = "UPDATE_TICKET_STATUS_FAILURE";
